export default {
  name: "RootTokenContract",
  abi: {
    "ABI version": 2,
    version: "2.1.0",
    header: ["pubkey", "time", "expire"],
    functions: [
      {
        name: "constructor",
        inputs: [
          { name: "name", type: "string" },
          { name: "symbol", type: "string" },
          { name: "decimals", type: "uint8" },
          { name: "root_public_key", type: "uint256" },
          { name: "root_owner", type: "address" },
          { name: "total_supply", type: "uint128" },
        ],
        outputs: [],
        id: "0xa",
      },
      {
        name: "setWalletCode",
        inputs: [
          { name: "_answer_id", type: "uint32" },
          { name: "wallet_code", type: "cell" },
        ],
        outputs: [{ name: "value0", type: "bool" }],
        id: "0xb",
      },
      {
        name: "deployWallet",
        inputs: [
          { name: "_answer_id", type: "uint32" },
          { name: "pubkey", type: "uint256" },
          { name: "internal_owner", type: "address" },
          { name: "tokens", type: "uint128" },
          { name: "grams", type: "uint128" },
        ],
        outputs: [{ name: "value0", type: "address" }],
        id: "0xc",
      },
      {
        name: "deployEmptyWallet",
        inputs: [
          { name: "_answer_id", type: "uint32" },
          { name: "pubkey", type: "uint256" },
          { name: "internal_owner", type: "address" },
          { name: "grams", type: "uint128" },
        ],
        outputs: [{ name: "value0", type: "address" }],
        id: "0xd",
      },
      {
        name: "grant",
        inputs: [
          { name: "_answer_id", type: "uint32" },
          { name: "dest", type: "address" },
          { name: "tokens", type: "uint128" },
          { name: "grams", type: "uint128" },
        ],
        outputs: [],
        id: "0xe",
      },
      {
        name: "mint",
        inputs: [
          { name: "_answer_id", type: "uint32" },
          { name: "tokens", type: "uint128" },
        ],
        outputs: [{ name: "value0", type: "bool" }],
        id: "0xf",
      },
      {
        name: "requestTotalGranted",
        inputs: [{ name: "_answer_id", type: "uint32" }],
        outputs: [{ name: "value0", type: "uint128" }],
        id: "0x10",
      },
      {
        name: "getName",
        inputs: [],
        outputs: [{ name: "value0", type: "string" }],
        id: "0x11",
      },
      {
        name: "getSymbol",
        inputs: [],
        outputs: [{ name: "value0", type: "string" }],
        id: "0x12",
      },
      {
        name: "getDecimals",
        inputs: [],
        outputs: [{ name: "value0", type: "uint8" }],
        id: "0x13",
      },
      {
        name: "getRootKey",
        inputs: [],
        outputs: [{ name: "value0", type: "uint256" }],
        id: "0x14",
      },
      {
        name: "getTotalSupply",
        inputs: [],
        outputs: [{ name: "value0", type: "uint128" }],
        id: "0x15",
      },
      {
        name: "getTotalGranted",
        inputs: [],
        outputs: [{ name: "value0", type: "uint128" }],
        id: "0x16",
      },
      {
        name: "hasWalletCode",
        inputs: [],
        outputs: [{ name: "value0", type: "bool" }],
        id: "0x17",
      },
      {
        name: "getWalletCode",
        inputs: [],
        outputs: [{ name: "value0", type: "cell" }],
        id: "0x18",
      },
      {
        name: "getWalletAddress",
        inputs: [
          { name: "pubkey", type: "uint256" },
          { name: "owner", type: "address" },
        ],
        outputs: [{ name: "value0", type: "address" }],
        id: "0x19",
      },
      {
        name: "getWalletCodeHash",
        inputs: [],
        outputs: [{ name: "value0", type: "uint256" }],
        id: "0x1a",
      },
    ],
    fields: [
      { name: "__uninitialized", type: "bool" },
      { name: "name_", type: "string" },
      { name: "symbol_", type: "string" },
      { name: "decimals_", type: "uint8" },
      { name: "root_public_key_", type: "uint256" },
      { name: "total_supply_", type: "uint128" },
      { name: "total_granted_", type: "uint128" },
      {
        components: [{ name: "dict_", type: "cell" }],
        name: "wallet_code_",
        type: "tuple",
      },
      { name: "owner_address_", type: "optional(address)" },
      { name: "start_balance_", type: "varuint16" },
    ],
    events: [],
  },
  image:
    "te6ccgECZQEAHhgAAgE0AwEBAcACAEPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAij/ACDBAfSkIFiS9KDgXwKKIO1T2QYEAQr0pCD0oQUAAAIBIDcHAgL9NQgCASA2CQE1NMAjoACwACZcHAjAVURVQLZ4IECANcYcSPZgCgEwIdMAjoACwACZcHAjVREBVRHZ4NP/cSPZCwSYbe1ABsMAA9M/0x/TH5UB7VDbMCLBE46A4SLBDo6A4SLBC46A4QLACvKpBvKoBPLgRFsG+QFAc/kQwADyaO1E0NMAMMAA8n74AHD4ZCMaDwwCkNs8IsAAjoAgWQFVAeEi0wEhwQOYMMAD8tBj8jThAcAC8rTTAAHAAJ4w0gfT/zDAAPLQajAg2SBZAVUB4AHTBAHXGAEwIVUB2T0NAUIwI8EE8uBtIdMBIcEDmDDAA/LQY/I04QHAAvK00wABwAAOAP6Oa8hwIQHPCwBwIQHPCz8azBjMFssHAdIHUFLL/wHT/+1HbxACwABQQ8t/cM8Lfxv0AApvF28QjhcwF/oCyVAJzMntVHpVUFUHVRlfCVUB2SIh4HEYzwsAFM4mcFUhXhBVCFUWVQVVB1UIVQjZIFkBVQHgAdMEAdcYATAhVQHZAo4iwQyOgOEH8qgF8uBEWwf5AVQQhPkQwADyaO1E0NMAAcAA8r/TP9TU0wfT/9N/03/0BNXTAI6AAsAAlnAicFUg2eD6QHEj2RIQAf4B+gDRLFYTvg3DAFANsPJ8+COBA+iogggbd0CgVhIBuXAhgBRhVQHjBAHyvHD4ZA3THyDXS8AA8tBDMNTRAsAA8uBoMFLouvLgZF8DbsAA+ADy0Gwi+QCC8FMAvltcOzDJ1ZL5gWRz14ch3+0CXKHJDECv9gdW+kaOuvLgaw7QEQDK0wEBwALIAfKwcyEBzwsBcCIBzwsBydABzgL6QDBQAs6AFxLPCyBxEs8LYQHJAczJcPsAyHDPCwBRd8s/UHb6AlBFzBLMywcVy/8Sy38Yy38S9AAGyVAGzMntVIALAVUSXwNVAdkBjALADPKpBvKoBPLgRDAH+QFUEIT5EMAA8mjtRNDTAAHAAPK/0z/U1NMH0//Tf9N/9ATV0wCOgALAAJZwInBVINng+kBxI9kTAvoB+gDRLFYTvg3DAFANsPJ8+COBA+iogggbd0CgVhIBuXAhgBRhVQHjBAHyvHD4ZA7TH9s8BcAA8uBoVhJVC7ry4GRSCqBToLn4APLQZSHTAfgoIsEDmFvAA/LQY/I04QLAAvK00wABwACOgCBZAVUB4AHTBAHXGAEwIVUB2U4UAXAwIdMBAtIH0/8wwAAiwQOYW8AD8tBj8jThAsAC8rQwAdMAjoACwACVISNwWdkhAeAh0wQB1xgk2RUBoMhwIQHPCwBwIQHPCz9WFwHMU5LOVhdVAcxWFgHLB3DPC38E0gcwVhxVBMv/Hcv/joCOECNVBTAhVQFVVlUMVTlVG9kqAeBxJQHPCwAdzizZFgGCVhMBzFHTygfJUA3MyQHMyXESzwsBC8zJVhBVCsxxzwsAIQHMcM8LAMn5AI6AJSHgBtMEAdcYATAmAVVBVQZVBtkXAfwwC/hk+ESCEIAAAAAhsYIQ/////xK8cFjjBMhwIQHPCwGADyIBzwsfE8sfAslwEs8LAHQVzwsCB9IHMFAHygccy//J0HYjAc8LAgbQgB9h0IATYVUNy38B0wFQOc5xFs8LASMDwAJQws5WElULzFJHzi76AoAdYQH0AHD6AnAYAf76AnPPC2FxF88LABXMcM8LAMlQBcxxzwsAUMPLf8lQAszJcPsACfhiyAHysHMhAc8LAXAiAc8LAcnQAc4E+kAwUATOgAyADBXPCx8ZznEZzwthCMlQCMzJcPsAyHDPCwCAEmEhyz8BgBFh+gJVD1UBzB/MHcsHH8v/Gst/Est/GQAkF/QACclQCczJ7VRVCVULXwrZA5oiwRGOgOEiwQ+OgOEH8qgF8uBEWwf5AVQQhPkQwADyaO1E0NMAAcAA8r/TP9TU0wfT/9N/03/0BNXTAI6AAsAAlnAicFUg2eD6QHEj2SAdGwL+AfoA0SxWE74NwwBQDbDyfPgjgQPoqIIIG3dAoFYSAblwIYAUYVUB4wQB8rxw+GQN0x8CwAAC2zwE8uBoVhFVCrry4GRSCaBTkLny0GX4AMh2IQHPCwNwIgHPCwHJ0PhEAs6CEIAAAAAisYIQ/////xO8cEED4wSADxPPCx/4KFscAMoDzwsfUkLOAgRQJvoCgBVhAfQAcPoCcPoCcc8LYQrPC38SznDPC3/JUAjMyXD7ADD4YshwzwsAUbvLP1C6+gJQicwWzBTLBxnL/8t/F8t/FvQAAslQAszJ7VSADllVE1UWXwYB2QGMAsAP8qkG8qgE8uBEMAf5AVQQhPkQwADyaO1E0NMAAcAA8r/TP9TU0wfT/9N/03/0BNXTAI6AAsAAlnAicFUg2eD6QHEj2R4BsgH6ANEsVhO+DcMAUA2w8nz4I4ED6KiCCBt3QKBWEgG5cCGAFGFVAeMEAfK8DtMfINdLcPhkIcJ/joAgWQFVAeBxErry4EMBwADy4EIB1SJwVREBVREBVQPZHwH+XwPTf9ECwADy4GgwUui68uBk+ABfAw/Q0wEBwALIAfKwcyEBzwsBcCIBzwsBydABzgL6QDBQAs6AHxLPCyBxEs8LYQHJUEOgUCPMyXD7AMhwzwsAUYjLPxXME8zLBxbL/xXLfxTLf1Aj+gJQcvQAAckBzMntVIAPAVUSXwNVAV0BBgLBEiEB/I577UTQ0wABwADyv9M/1NTTB9P/03/Tf/QE1dMAAcAAjkww+gDRcPhkXwdVD9DTAQHAAsgB8rBzIQHPCwFwIgHPCwHJ0AHOAvpAMFACznHPC2GAEoASE88LHxPMyVACzMlw+wBVIFVkVSxfDQHZIFkBVQHgAfpAATAhVQHZ4SIA9u1E0NMAAcAA8r/TP9TU0wfT/9N/03/0BNXTAAHAAI5MMPoA0XD4ZF8ID9DTAQHAAsgB8rBzIQHPCwFwIgHPCwHJ0AHOAvpAMFACznHPC2GAEYARE88LH4ARYQHMyQHMyXD7AFlVY1UrXwwB2SBZAVUB4AH6QAEwIVUB2QMeIsEXjoDhIsEVjoDhAsEUKSYkAf6Ofe1E0NMAAcAA8r/TP9TU0wfT/9N/03/0BNXTAAHAAI5OMPoA0XD4ZF8FgBJh0NMBAcACyAHysHMhAc8LAXAiAc8LAcnQAc4C+kAwUALOcc8LYYAUgBQTzwsfE8v/yVACzMlw+wBVQFVmVS5fDwHZIFkBVQHgAfpAATAhVQHZJQD84e1E0NMAAcAA8r/TP9TU0wfT/9N/03/0BNXTAAHAAI5OMPoA0XD4ZF8GgBFh0NMBAcACyAHysHMhAc8LAXAiAc8LAcnQAc4C+kAwUALOcc8LYYATgBMTzwsfE8sHyVACzMlw+wBVMFVlVS1fDgHZIFkBVQHgAfpAATAhVQHZAv4CwRaOgOHtRNDTAAHAAPK/0z/U1NMH0//Tf9N/9ATV0wABwACOTzD6ANFw+GRfBIATYdDTAQHAAsgB8rBzIQHPCwFwIgHPCwHJ0AHOAvpAMFACznHPC2GAFYAVE88LHxPLf8lQAszJcPsAVVBVZ1UvgBBlAdkgWQFVAeAB+kABKCcACjAhVQHZAf7tRNDTAAHAAPK/0z/U1NMH0//Tf9N/9ATV0wABwACOUTD6ANFw+GRfA4AUYdDTAQHAAsgB8rBzIQHPCwFwIgHPCwHJ0AHOAvpAMFACznHPC2GAFoAWE88LHxPLf8lQAszJcPsAVWBVaHOAEWOAEWUB2SBZAVUB4AH6QAEwIVUBXQNUIsEZjoDhAsEYjoDh7UTQ0wABwADyv9M/1NTTB9P/03/Tf/QE1dMAAcAALCsqANCOVzD6ANFw+GRbgBVh0NMBAcACyAHysHMhAc8LAXAiAc8LAcnQAc4C+kAwUALOgBdxEs8LYYAXE88LHwNuwABxsBPPCwDJAczJcPsAVXBVaXOAEmOAEmUB2SBZAVUB4AH6QAEwIVUB2QD87UTQ0wABwADyv9M/1NTTB9P/03/Tf/QE1dMAAcAAjk8w+gDRcPhkW4AVYdDTAQHAAsgB8rBzIQHPCwFwIgHPCwHJ0AHOAvpAMFACznHPC2GAGIAYE88LHxPMyVACzMlw+wBVcFVpc4ASY4ASZQHZIFkBVQHgAfpAATAhVQHZAmoiwRqOgOHtRNDTAAHAAPK/0z/U1NMH0//Tf9N/9ATV0wABwACOgCBZAVUB4AH6QAEwIVUB2TMtAdow+gDRcPhkWynXS46AgQNOIwG8jk6BAP8jAbyOITAM0/8g10shwSxWEOFxuvLgQ8AA8uBC1S5wVREBVREB2SBZAVUB4HETuvLgQwLAAPLgQgvVLHBVAVWEVQtVClUMVQ1VDdnhDNP/LXBwVQHZLgFqW/pA+CgB0SHTASHBA5gwwAPy0GPyNOEBwALytNMAAcAAjoAgWQFVAeAB0wQB1xgBMCFVAdkvAXAwIdMBAtIH0/8wwAAiwQOYW8AD8tBj8jThAsAC8rQwAdMAjoACwACVISNwWdkhAeAh0wQB1xgk2TABrMhwIQHPCwBwIQHPCz+AFGEBzFGSzoATYVUJzIASYQHLB3DPC38E0gcwgBFhVQTL/xvL/46AjhIjVQUwIVUBVRlVGFUKVTdVGdkqAeBxJQHPCwAbzirZMQFOLgHMUbPKB8lQC8zJAczJcRLPCwEJzMlQuMxxzwsAF8xwzwsAyfkAMgDgjlowgBth0NMBAcAC8rBzKwHPCwFwLAHPCwHJ0AHOAfpAMAHOgBlxEs8LYYAZLAHPCx90Hc8LAgXSBzBQBcoHEsv/ydBQCs7JUALMyXD7AFUnVYtzgBZjgBZlAdkiIeAD0wQB1xgBMCMBVRFVA1UD2QH+AsAa8qntRNDTAAHAAPK/0z/U1NMH0//Tf9N/9ATV0wABwACOVDD6ANFw+GRbgBVh0NMBAcACyAHysHMhAc8LAXAiAc8LAcnQAc4C+kAwUALOcc8LYYAagBoTzwsfA/kAE88L/8lQAszJcPsAVXBVaXOAEmOAEmUB2SBZAVUB4DQAEgH6QAEwIVUB2QIBIDY2AAU8jaACpN8B0NMAAcAA8rAg1gHTAJbtQO1Q2zACwACOgOAwA9IfAcD/+ADy4GbTHwHAD/LgZtMf7UTQ0wABwAAC038wAvK/0z/U1NMH0//Tf9N/9ATV0wA5OADsjmEB+gDRU2258tBnyHAhAc8LAFHuyz8dzBvMGcsHUFyhUGvL/wbAAFBGy38Zy38Y9ACOEzBQZPoCyVADzMntVHBVcF8IAdkkIeBxF88LABjOJXBVB1USAVUkVQVVCFUIVQjZAsAAmXBwIwFVEVUC2eD6QHEj2QSwMCPXDR9vo8AAmHBZVSNfBQHZ4DAk10nAAPJwwACXcFUhXwMB2eBtBNMfmHBZVSNfBQHZIsENjoDhIsELjoDhAsAKIuHtRNDTADDAAPJ++ABw+GTbPCLAAE9DPToBho6AIFkBVQHhItMBIcEDmDDAA/LQY/I04QHAAvK00wABwACeMNIH0/8wwADy0GowINkgWQFVAeAB0wQB1xgBMCFVAdk7AUIwI8EE8uBtIdMBIcEDmDDAA/LQY/I04QHAAvK00wABwAA8APiOaMhwIQHPCwBwIQHPCz8azBjMFssHAdIHUFLL/wHT/+1HbxACwABQQ8t/cM8Lfx30AAxvF28QjhQwF/oCyVALzMntVHpVUFUnXwkB2SIh4HEYzwsAFM4mcFUhXhBVCFUWVQVVB1UIVQjZIFkBVQHgAdMEAdcYATAhVQHZAYog10uBA9YiAbwhwgLtQJ9b03/RCe1QVSRVSF8IVQRRMrCOgOEF1NTTB9P/+kAncF9QVR5VHgFVCIARYVUnVVtVHoARYdk+AZ6BA1YlAbyOIlv6QCDXS4EAgCIBuS7hcbry4EPAAPLgQtUscFURAVURAdlRE7COgOEG1NTTB9P/KnBfQFUdVR0BVQdVDlUPVRhVS1UdVQ/ZPwGUgQEHJgG8jh9b0/8g10shwSwq4XG68uBDwADy4ELVKHBVEQFVEQHZURSwjoDhB9TU0wcqcF8wVRxVHAFVBlUcVQ5VCVU7VRxVDtlAAYwmwgeOIlvTByDXS4EBACIBuSjhcbry4EPAAPLgQtUmcFURAVURAdlRFbCOgOEI1NQqcF8gVRtVGwFVBVUqVQ1VK1UbVQ3ZQQH+jh3UINdLIcEIJuFxuvLgQ8AA8uBC1SRwVREBVREB2Y5ZjihxGboJwABQCbAncHBVB1UBVQhVAlU1VRlVGeEK1QEwKgFVgVUKVQrZjhkwCdQg10sgwADy0ENxugHAALAr4dUBMCrZKcEClynAAiFVAuLhKcAA8tBDAdkmAeEJ1EIABCrZAm4wAcEMjoDh7UTQ0wABwADyv9M/1NTTB9P/03/Tf/QE1dMAjoACwACZcHAjAVURVQLZ4PpAcSPZRkQB/gH6ANEN0x9w+GQg10vAAPLQQzDU0QLAAPLQaVUP0wDTANMA+kBTcccFwAAB+kD6ADAC8tBkMApuwAD4APLQbCX5AILwUwC+W1w7MMnVkvmBZHPXhyHf7QJcockMQK/2B1b6Ro668uBr7UdvEG8XbxAaonL7Ash2IQHPCwNwIgFFANjPCwHJ0AHOGs5w+gKAFGEB9ABQScsfcBn6AnEZzwsAcBn6AgjJcRnPC2EYzMmBAID7AMhwIQHPCwAfyz9xH88LABTOUM3MGswYywcWy/8Uy38Sy38V9ABQZ/oCyVAGzMntVIALVUBVBl8GAdkBYO1E0NMAAcAA8r/TP9TU0wfT/9N/03/0BNXTAI6AAsAAmXBxI1URAVUR2eD6QHAj2UcC8AH6ANFw+GQN0x/bPAXy0GmAE2HTANMA0wD6QFOhxwXAAAH6QPoAMALy0GQwUl+gU/C5+ADy0GUm0wHtR/goAW8QbxdvEIASYQGicvsCIsEDmFvAA/LQY/I04QLAAvK00wABwACOgCBZAVUB4AHTBAHXGAEwIVUB2U5IAXAwIdMBAtIH0/8wwAAiwQOYW8AD8tBj8jThAsAC8rQwAdMAjoACwACVISNwWdkhAeAh0wQB1xgk2UkBpMhwIQHPCwBwIQHPCz9WHAHMUZLOVhtVCcxWGgHLB3DPC38E0gcwVhlVBMv/gBFhAcv/joCdJFUGMCFVl4ASYVV62SsB4HEmAc8LAIASYQHOIdlKAYZWFwHMUTXKB8lQA8zJUAPMyXEUzwsBUDLMyVYUVQHMcc8LACEBzHDPCwDJ+QCOgCYh4AfTBAHXGAEwJwFVUVUHVQfZSwH+MC/4ZPhEdBXPCwKCEIAAAAAlsYIQ/////xa8CNIHcEoH4wQIzwoHyHAhAc8LAFAyy//JgA8jAc8LHxnLHwjQdiIBzwsCcBTPCwHJ0FADzlUPVQjLf3ETzwsBI1LUzlYWVQHMUkPOVhL6AlYgAfQAcPoCcPoCc88LYXETzwsAFUwB/sxwzwsAyQHMcc8LAFUPVQPLf8kBzMlw+wD4YshR3csfznYtAc8LA3AezwsBydAByQ3OGM5w+gKAGWEB9ABw+gJw+gJxzwthG8zJgQCA+wDIcCEBzwsAgBVhAcs/cRLPCwAczoATYVULzIASYQHMgBFhAcsHVQ8By/8fy38Vy39NADAc9ABQzfoCyVAMzMntVIAMVaBVDF8MAdkBviDXS4487UAD038g10uBAIAiAbmeXwPTf9EE7VBZVTVfBgEgWQFVAeFxErry4EMBwADy4EIB1SJwVREBVREBVQPZgQPOIwG8joDhA9P/+kAlcF8gVRZVEwFVJVUWVQjZUQN6IsEPjoDhMAHBDo6A4e1E0NMAAcAA8r/TP9TU0wfT/9N/03/0BNXTAI6AAsAAmXBwIwFVEVUC2eD6QHEj2V5YUAJaAfoA0Q3THyDXS3D4ZI6AgQPOIwG8joDhA9P/+kAlcF8gVRZVEwFVJVUWVQjZUlEA/I4iW/pAINdLgQCAIgG5JuFxuvLgQ8AA8uBC1SRwVREBVREB2YEDTiQBvI5IgQD/JAG8jiAwBNP/INdLIcEsKOFxuvLgQ8AA8uBC1SZwVREBVREB2SBZAVUB4HEUuvLgQwPAAPLgQgPVInBVEQFVAVUjVQXZ4QTT/yVwcFUB2QGy7UdvEG8X+Cgl0wEDgB1h0wAI03/RBAjTANMA+kD6QPoAMAZvEBaicvsCJcEDmV8FwAPy0GPyNOEFwALytF8EAtMAAcAAjoAgWQFVAeAB0wQB1xgBMCFVAdlTAXAwJdMBAtIH0/8wwAAiwQOYW8AD8tBj8jThAsAC8rQwAdMAjoACwACVISNwWdkhAeAh0wQB1xgk2VQBpMhwIQHPCwBwIQHPCz9WHwHMUdLOVh5VDcxWHQHLB3DPC38E0gcwVhxVBMv/H8v/joCOEiNVBTAhVQFVHVVYVQ5VO1Ud2SoB4HElAc8LAB/OLtlVAYJWGQHMUfPKB8lQD8zJAczJcSIBzwsBDszJVhdVDcxxzwsAzHDPCwDJIPkAjoAmIeAH0wQB1xgBMCcBVVFVB1UH2VYB/nQlAc8LAnYVzwsCcCYBzwsBydAJ0gcwUJnOUITKB3AVzwsfBMv/ydBSA84DyYATYcAAUEr6AlYhAfQAcPoCcPoCc88LYcxxzwsAEszJcPsAyFUPIcsfEs52IgHPCwNwE88LAcnQAckCzhjOcPoCgB1hAfQAcPoCcPoCcc8LYRdXAOTMyYEAgPsAyHAhAc8LAIAZYSHLP4AZYQHMgBhhAcyAF2EByweAFmEBy/+AFWEBy3+AFGEBy3+AE2EB9ACOGjABgBNh+gLJAczJ7VSADYARYoATYYASZQHZKCHgcRTPCwCAEWEBziNwVQMBVRIBVQRVBNkBYO1E0NMAAcAA8r/TP9TU0wfT/9N/03/0BNXTAI6AAsAAmXBxI1URAVUR2eD6QHAj2VkC/gH6ANFw+GQN0x/bPDAD8tBpgBFh0wDTANMA+kBTgccFwAAB+kD6ADAC8tBkMFJ9oFPQufLQZe1HbxBvF/gAbxAmDqFy+wL4RIIQgAAAACGxghD/////ErxwWOMEyHYhAc8LA3AiAc8LAcnQgA8TzwsfE8sfAs4XznD6AoAXYQFbWgCy9ABw+gJw+gJxzwthUIbLf85wzwt/yVAEzMmBAID7AF8EBfhiyHAhAc8LABzLP3EczwsAzlCazBfMFcsHE8v/y3/Lf/QAUDT6AslQA8zJ7VSADllVA18DAdkBbCDXS+1An1vTf9EE7VBVAVUjXwRVAYEDTiQBvI6A4QT6QNN/JnBfIFUXVQNVCFUJVSdVF1UJ2VwB/o4iW9N/INdLgQCAIgG5JuFxuvLgQ8AA8uBC1SRwVREBVREB2YECziUBvI5KJMEsjiMwBfpAINdLgQCAIgG5KeFxuvLgQ8AA8uBC1SdwVREBVREB2SBZAVUB4XEVuvLgQwTAAPLgQgTVI3BVEQFVAVUDVSRVBtnhBfpAJnBwVQFdAALZAmwiwRCOgOHtRNDTAAHAAPK/0z/U1NMH0//Tf9N/9ATV0wCOgALAAJlwcCMBVRFVAtng+kBxI9liXwFiAfoA0Q7THyDXS3D4ZCHCf46AIFkBVQHgcRK68uBDAcAA8uBCAdUicFURAVURAVUD2WAB/F8D03/RAsAA8tBpgBJh0wDTANMA+kBTcccFwADy0GTtR28QbxcB+kD4APoAMAJvEFCOoA2icvsCyHYhAc8LA3AiAc8LAcnQAc4SznD6AoAXYQH0AAXPCx9wFfoCcRXPCwBwFfoCBMlxFc8LYRTMyYEAgPsAyHAhAc8LAFUPAWEAaMs/H8wdzBvLBxnL/xfLf3EbzwsAUFrLf1BJzlAo9ABQefoCyVAIzMntVIAPVXBVCV8JAdkBagLAECLh7UTQ0wABwADyv9M/1NTTB9P/03/Tf/QE1dMAjoACwACZcHEjVREBVRHZ4PpAcCPZYwH+gBFh0wAD+gDRA9MA7UdvEG8XAdMA+kD6QHD4ZPoAMARvEIAUYdMfMAWhcvsCyHYhAc8LA3AiAc8LAcnQAc4TznD6AoAXYQH0AFBCyx9wEvoCURzPC39wEvoCAclxEs8LYczJgQCA+wDIcCEBzwsAgBJhIcs/gBJhAcyAEWEBzGQAlFUPAcsHH8v/Hct/G8t/GfQAjhYwULT6AslQA8zJ7VSAEFWQVQtfCwHZJCHgcRzPCwAWzipwVTFeIFUMVRpVCFUaVQlVC1UMVQzZ",
};
